### ISSUE TITLE
If you enter tactical mode while being out of range from any enemies it breaks

### ISSUE THREAD

**Issue by pabloruiz55** [mixandjam/FFVII-TacticalMode#1]
If you enter tactical mode while being out of range from an enemy it breaks (camera bugs, pointing to character, and if you confirm the ATB bar is spent)

How to reproduce:

1. Fill the ATB gauge
2. Move far away from all enemies
3. right-click to enter tactical mode

You will see the camera doesn't point to any enemy and doing an attack inside this mode spends the gauge without doing anything.

**Comment by mixandjam** [comment]
Thanks Pablo! Fixed!
